---
title: "gallery"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, include = FALSE}
library(tidyverse)
library(pixture)
library(slickR)
```


## Gallery of Images

This software "miniturizes" the images into thumbnails automatically.
When you click on individual images, it "pops-up" in a lightbox.

```{r echo = FALSE}
list_photo1 <-
  c("Picture1.jpg",
    "Picture2.jpg",
    "Picture3.jpg",
    "Picture4.jpg",
    "Picture5.jpg",
    "Picture6.jpg",
    "Picture7.jpg",
    "Picture8.jpg",
    "Picture9.jpg",
    "Picture10.jpg",
    "Picture11.png",
    "Picture12.png",
    "Picture13.png",
    "Picture14.png",
    "Picture15.png",
    "Picture16.png",
    "Picture17.png",
    "Picture18.png",
    "Picture19.png",
    "Picture20.png")

pixgallery(list_photo1)


```
<hr>
Or it can be arranged as a scrollbar.

```{r echo = FALSE}
slick_list_photos <-
  list("Picture1.jpg",
    "Picture2.jpg",
    "Picture3.jpg",
    "Picture4.jpg",
    "Picture5.jpg",
    "Picture6.jpg",
    "Picture7.jpg",
    "Picture8.jpg",
    "Picture9.jpg",
    "Picture10.jpg",
    "Picture11.png",
    "Picture12.png",
    "Picture13.png",
    "Picture14.png",
    "Picture15.png",
    "Picture16.png",
    "Picture17.png",
    "Picture18.png",
    "Picture19.png",
    "Picture20.png")

options <-
  settings(dots = TRUE,
           initialSlide = 0,
           slidesToShow = 5,
           slidesToScroll = 5,
           focusOnSelect = TRUE)

slickR(obj = slick_list_photos, height = 150, width = "90%") +
  options
```