---
title: "Nikkei 225 Open Interest by Trading Participant 2023-12-29"
description: |
date: 2024-01-04

categories:
  - nikkei225
  - options
output:
  distill::distill_article:
    toc: true
    toc_depth: 6
    toc_float: true    
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo = FALSE, include = FALSE}


# Remove all objects in workspace ----
rm(list = ls())

#setwd("C:/Users/User/Dropbox/Papa Work/Data Science/R/SMU/Readings")

# Please import necessary libraries ----
#pacman::p_unload("all")

#### Set up dependencies (Activate necessary packages) ----
pacman::p_load(tidyverse, lubridate,glue, forcats, knitr, rmarkdown,
               scales, gridExtra, ggthemes, ggrepel, cowplot, magick, plotrix, 
               patchwork, hexbin,
               data.table, styler, DT, blogdown,
               quantmod, bizdays, roptions, #plotly,
               gtrendsR,rvest, Rcrawler, RCurl, httr2, crul, jsonlite, RSelenium, httr,
               mapdata, maps, ggmap,
               tidytext, wordcloud2, igraph, ggraph, textdata, tm, haven, readxl,
               jtools, huxtable, broom, modelr, skimr, psych, Hmisc, texreg, GGally,
               randomForest, gvlma, ggfortify, sandwich, car, ggstance, broom.mixed,
               interactions,
               blogdown)


theme_set(theme_clean())
sessionInfo()


# Import Data ----
# download weekly report. Issued every friday ----
download_date <- "20231229"
#  format(today(), "%Y%m%d")

#URL <- glue("https://www.jpx.co.jp/english/markets/derivatives/participant-volume/o4sio7000000346f-att/{download_date}_volume_by_participant_whole_day.xlsx")
file_name <- glue("{download_date}_nk225op_oi_by_tp_e.xlsx")
#GET(URL, write_disk(file_name, overwrite=TRUE))

data <- read_excel(file_name,
                   sheet = "BO_DD0123",
                   skip = 5)
names(data)
# seperate to put and call dataframe

data_p <-
  data %>%
  select(2:8)

data_c<-
  data %>%
  select(12:18)

# seperate to net selling vs net buying df

data_p_ns<-
  data_p %>%
  select(1,3,4) %>%
  drop_na() %>%
  rename(strike = "PUT January 2024",
         participant_name = "...4",
         volume = "...5") %>%
  mutate(volume = -1*volume,
         type = "P")


data_p_nb <-
  data_p %>%
  select(1,6,7) %>%
  drop_na() %>%
  rename(strike = "PUT January 2024",
         participant_name = "...7",
         volume = "...8") %>%
  mutate(type = "P")

data_c_ns<-
  data_c %>%
  select(1,3,4) %>%
  drop_na() %>%
  rename(strike = "CALL January 2024",
         participant_name = "...14",
         volume = "...15") %>%
  mutate(volume = -1*volume,
         type = "C")

data_c_nb <-
  data_c %>%
  select(1,6,7) %>%
  drop_na() %>%
  rename(strike = "CALL January 2024",
         participant_name = "...17",
         volume = "...18") %>%
  mutate(type = "C")

# combine all 4 into 1 dataset
data_weekly <-
  rbind(data_p_ns, data_p_nb, data_c_ns, data_c_nb)

# Read in data_cumulative and combine into one data set

# Since this is week one for 2311, data_23_11 is the same as data_weekly
# data_2401 <- data_weekly
# saveRDS(data_2401, file = "data_2401.RDS")
#
#
data_2401<-
  readRDS (file = "data_2401.RDS")



#for week 2, 3, 4, we need to merge and find new net position

d <-
  full_join (data_2401, data_weekly, by = c("strike", "type", "participant_name")) %>%
  mutate(volume = ifelse(is.na(volume.y), volume.x,
                         ifelse(is.na(volume.x), volume.y,
                                volume.x + volume.y)
                         )
         )
# check then select necessary columns (strike, participant, type, volume)

d<-
  d %>%
  select(-volume.x, -volume.y)
# # check if d is correct. IF yes, allocate to data_2311 and save
data_2401 <- d
saveRDS(data_2401, file = "data_2401.RDS")

# stging 1: look for strikes with volume greater than 2000
participant_strike2000 <-
  data_2401 %>% 
  filter(abs(volume)>=2000)

#Staging 2: filter for big players

participant_select <-
  data_2401 %>% 
  filter(participant_name %in% c("ABN AMRO Clearing Tokyo",
                                 "Societe Generale Securities Japan",
                                 "Goldman Sachs Japan")) %>%
  mutate(participant_name = factor(participant_name)
         )
# Join
data_reduced <-
  full_join (participant_strike2000, participant_select, by = c("strike", "type", "participant_name")) %>% 
  mutate(volume = ifelse(is.na(volume.x), volume.y, volume.x)
         ) %>% 
  select(-volume.x, -volume.y)
n_distinct(data_reduced$participant_name)

# Lets get x axis paramenters
x_min <- min(data_reduced$strike)
x_max <- max(data_reduced$strike)

p_trading_participant_OI <-
  ggplot(data = data_reduced,
       aes(x = strike,
           y = volume,
           fill = type)
       )+
  geom_col(position = "dodge") +
  scale_fill_manual(values = c("blue", "red"),
                    )+
  scale_x_continuous(name = "strike",
                   limits = c(x_min, x_max),
                   breaks = seq(from = x_min, to = x_max, by = 125)
                   )+
  facet_wrap(.~ factor(participant_name),
             ncol = 1)+
  # facet_wrap(.~ factor(participant_name, c("ABN AMRO Clearing Tokyo",
  #                                          "Societe Generale Securities Japan",
  #                                          "Goldman Sachs Japan")),
  #            ncol = 1)+
  labs(title = "Net Options Position by Trading Participant",
       subtitle = "January 24 contract",
       caption = "Source = https://www.jpx.co.jp/english/markets/derivatives/participant-volume/index.html")+
  theme(legend.text = element_text(size = rel(0.4)),
        legend.title = element_text(size = rel(0.4)),
        legend.position = "right",
        plot.title = element_text(size = rel(0.8)),
        plot.subtitle = element_text(size = rel(0.7)),
        plot.caption = element_text(size = rel(0.6)),
        axis.text.y = element_text(size = rel(0.5)),
        axis.text.x = element_text(angle = 45, size = rel(0.5)),
        strip.text = element_text(size = rel(0.6)),
        axis.title = element_text(size = rel(0.6)))+
  coord_flip()
 
```
```{r, layout="l-page", fig.width = 8, fig.height=12}
p_trading_participant_OI
```