---
title: "Predict future sales: Final project for Coursera course"
description: |
  A short description of the post.
draft: True
date: 2024-03-29
categories:
  - regression
  - random forest
  - lightgbm
  - knn
  - xgboost
output:
  distill::distill_article:
    toc: true
    toc_depth: 6
    toc_float: true    
    self_contained: false
editor_options: 
  chunk_output_type: console
---

```{css, echo = FALSE}
d-byline {
  display: none;
  margin:0;
}

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(results = FALSE, echo = TRUE, eval = FALSE, fig.width = 6, layout="l-body-outset")
```


```{r}
rm(list=ls())
pacman::p_load("tidyverse", #for tidy data science practice
               "tidymodels", "workflows", "finetune", "themis", "embed", "butcher",# for tidy machine learning
               "pacman", #package manager
               "devtools", #developer tools
               "Hmisc", "skimr", "broom", "modelr",#for EDA
               "jtools", "huxtable", "interactions", # for EDA
               "ggthemes", "ggstatsplot", "GGally",
               "scales", "gridExtra", "patchwork", "ggalt", "vip",
               "ggstance", "ggfortify", # for ggplot
               "DT", "plotly", #interactive Data Viz
               # Lets install some ML related packages that will help tidymodels::
               "usemodels", "poissonreg", "agua", "sparklyr", "dials", "bonsai",#load computational engines
               "doParallel", # for parallel processing (speedy computation)
               "ranger", "xgboost", "glmnet", "kknn", "earth", "klaR", "discrim", "naivebayes", "baguette", "kernlab", "lightgbm",#random forest
               "janitor", "lubridate")

```


```{r}
df <-read.csv("sales_train.csv")
skim(data_train)

```

```{r}
data_train <-
  df %>% 
  mutate(date = lubridate::dmy(date)) %>% 
  group_by(date_block_num, shop_id, item_id) %>% 
  dplyr::summarise(num_sold = sum(item_cnt_day)) %>%
  pivot_wider(id_cols = c("date_block_num", "shop_id"),
              names_from = "item_id",
              names_prefix = "item_",
              values_from = "num_sold",
              values_fill = 0) %>% 
  mutate(item_cnt_month = sum(across(starts_with("item_")))) %>% 
  relocate()

```




